### ISSUE TITLE
Camera focus bugged in the Loadout screen

### ISSUE THREAD

**Issue by KongMD-Steam** [bountygiver/WaveCOM-WOTC#1]
The camera focus is bugged in the Loadout screen. Here's a save to reproduce the issue.

## Steps to reproduce error:
* Load up attached save
* Select any soldier > press Loadout
* TAB through the soldiers. The camera eventually gets stuck on Isaac for three iterations, then starts focusing on the soldiers again. This happened on multiple waves, not just this wave.
[WaveCom_Camera_Bug.zip](https://github.com/bountygiver/WaveCOM-WOTC/files/1783374/WaveCom_Camera_Bug.zip)

**Comment by bountygiver** [comment]
I have fixed some soldier selection issues in loadout screen, see if it happens again, also post a video of what is happening if it happened again because I can't exactly find out what's the problem.

**Comment by KongMD-Steam** [comment]
The error is still occurring when I build the project with the most recent commits. [Here's a video](https://gfycat.com/MammothYearlyBarnswallow).

**Comment by bountygiver** [comment]
oh you mean it didn't select them, so yeah because the game refuses to select units that run out of actions programmatically, I have been trying to find the solution to this problem way before WOTC is released, don't worry I am forcing the camera to focus on the correct unit on the next update.
